version: "3.8"
services:
  db:
    image: postgres:15
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    container_name: db_app
    env_file:
      - .env_none_dev

  redis:
    image: redis:7
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    container_name: redis_app
    env_file:
      - .env_none_dev

  app:
    build:
      context: .
#    image: bagroman/fastapi_repo:latest
    env_file:
      - .env_none_dev
    container_name: my_app
    command: ["/my_app/docker_cmds/app.sh"]
    ports:
      - "${PORT}:8000"
    depends_on:
      db:
        condition: service_healthy
